"use strict";

// Consumer test for the deterministic golden fixtures generated by
// scripts/generate-golden-fixtures.cjs.
//
// Two independent guarantees are checked here:
//   1. Drift: the committed envelope-v2-golden.json is byte-identical to
//      what the generator produces right now, so the fixture file can
//      never silently diverge from the generator that is supposed to own
//      it (mirrors the skip-inventory drift guard's approach for a
//      different generated artifact).
//   2. Behavior: each vector, when run through the REAL verifyV2Envelope
//      decoder, produces exactly the recorded expected verdict. This is
//      what makes the fixtures "golden" rather than just "deterministic":
//      they pin a specific decoder's specific behavior against specific
//      bytes, so a future change to verifyV2Envelope that alters accepted/
//      rejected outcomes for these exact vectors is caught here.

const assert = require("node:assert/strict");
const { describe, it } = require("node:test");

const { verifyV2Envelope } = require("../index.js");
const {
  buildFixtures,
  render,
} = require("../../../../../scripts/generate-golden-fixtures.cjs");
const fs = require("node:fs");
const path = require("node:path");

const FIXTURE_PATH = path.join(__dirname, "envelope-v2-golden.json");

describe("envelope-v2 golden fixtures (generated, deterministic)", () => {
  it("committed fixture file matches what the generator produces right now (no drift)", () => {
    const committed = fs.readFileSync(FIXTURE_PATH, "utf8");
    const fresh = render(buildFixtures());
    assert.equal(
      committed,
      fresh,
      "packages/agent/src/signing/fixtures/envelope-v2-golden.json has " +
        "drifted from scripts/generate-golden-fixtures.cjs; regenerate with " +
        "`node scripts/generate-golden-fixtures.cjs --update-golden`",
    );
  });

  const fixtures = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));

  for (const vector of fixtures.vectors) {
    it(`vector "${vector.name}": ${vector.description}`, () => {
      const verdict = verifyV2Envelope({
        envelope: vector.envelope,
        publicKeyPem: fixtures.publicKeyPem,
        pinnedSigningKeyId: fixtures.pinnedSigningKeyId,
      });

      assert.equal(verdict.allowed, vector.expected.allowed);
      if (vector.expected.allowed) {
        assert.deepEqual(verdict.job, vector.expected.job);
      } else {
        assert.equal(verdict.rejectionReason, vector.expected.rejectionReason);
      }
    });
  }

  it("has exactly the four required vectors (valid, tampered-payload, tampered-signature, wrong-key)", () => {
    const names = fixtures.vectors.map((v) => v.name).sort();
    assert.deepEqual(names, [
      "tampered-payload",
      "tampered-signature",
      "valid",
      "wrong-key",
    ]);
  });
});
