#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHART="${REPO_ROOT}/deploy/helm"
OUT="${REPO_ROOT}/.build/helm-template-verify"
RELEASE_NAME="${HELM_RELEASE_NAME:-tokentimer}"

if ! command -v helm >/dev/null 2>&1; then
  HELM_DIR="$(mktemp -d)"
  trap 'rm -rf "${HELM_DIR}"' EXIT
  curl -fsSL https://get.helm.sh/helm-v3.20.1-linux-amd64.tar.gz \
    | tar -xz -C "${HELM_DIR}"
  export PATH="${HELM_DIR}/linux-amd64:${PATH}"
fi

helm version

helm dependency build "${CHART}" 2>/dev/null || true

mkdir -p "${OUT}"

echo "==> helm lint (ci-values)"
helm lint "${CHART}" -f "${CHART}/ci/ci-values.yaml"

echo "==> helm show values -> ${OUT}/all-values.yaml"
{
  echo "# Generated by scripts/helm-template-verify.sh"
  echo "# helm show values ${CHART}"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  helm show values "${CHART}"
} > "${OUT}/all-values.yaml"

scenarios=(
  "defaults:${CHART}/values.yaml"
  "ci:${CHART}/ci/ci-values.yaml"
  "minimal:${CHART}/examples/values-minimal.yaml"
  "external-db:${CHART}/examples/values-external-db.yaml"
  "full-test:${CHART}/examples/values-full-test.yaml"
)

for item in "${scenarios[@]}"; do
  name="${item%%:*}"
  values="${item#*:}"
  dest="${OUT}/rendered-${name}.yaml"
  echo "==> helm template ${RELEASE_NAME} [${name}] -> ${dest}"
  set_args=(--set "config.adminEmail=ci@example.com")
  case "${name}" in
    external-db)
      set_args+=(--set "postgresql.external.password=dummy")
      ;;
  esac
  helm template "${RELEASE_NAME}" "${CHART}" \
    -f "${values}" \
    "${set_args[@]}" \
    > "${dest}"
  count="$(grep -c '^kind:' "${dest}" || true)"
  echo "    resources: ${count}"
done

echo "==> spot-check full-test render"
grep -n "kind: ConfigMap" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "TRUST_PROXY_HOPS" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "kind: HorizontalPodAutoscaler" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "kind: Cluster" "${OUT}/rendered-full-test.yaml" | head -3 || true

echo "==> assert DB_SSL=verify when CloudNativePG is enabled (defaults + minimal)"
for name in defaults minimal; do
  rendered="${OUT}/rendered-${name}.yaml"
  if ! grep -qE 'DB_SSL:[[:space:]]*"?verify"?' "${rendered}"; then
    echo "helm-template-verify: FAIL missing DB_SSL=verify in ${name} render" >&2
    grep -n 'DB_SSL\|cloudnative' "${rendered}" | head -20 >&2 || true
    exit 1
  fi
done

echo "helm-template-verify: ok -> ${OUT}"
