#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHART="${REPO_ROOT}/deploy/helm"
OUT="${REPO_ROOT}/.build/helm-template-verify"
RELEASE_NAME="${HELM_RELEASE_NAME:-tokentimer}"
HELM_VERSION="v3.20.1"
HELM_SHA256="0165ee4a2db012cc657381001e593e981f42aa5707acdd50658326790c9d0dc3"

if ! command -v helm >/dev/null 2>&1; then
  HELM_DIR="$(mktemp -d)"
  HELM_ARCHIVE="${HELM_DIR}/helm-${HELM_VERSION}-linux-amd64.tar.gz"
  trap 'rm -rf "${HELM_DIR}"' EXIT
  curl -fsSLo "${HELM_ARCHIVE}" \
    "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz"
  echo "${HELM_SHA256}  ${HELM_ARCHIVE}" | sha256sum -c -
  tar -xzf "${HELM_ARCHIVE}" -C "${HELM_DIR}" linux-amd64/helm
  export PATH="${HELM_DIR}/linux-amd64:${PATH}"
fi

helm version

helm dependency build "${CHART}" 2>/dev/null || true

mkdir -p "${OUT}"

echo "==> helm lint (ci-values)"
helm lint "${CHART}" -f "${CHART}/ci/ci-values.yaml"

# Regression guard for .github/workflows/release.yml's "Lint and template packaged
# chart" / "Verify Helm package" steps: those run helm lint/template against the
# *packaged* .tgz (not the source directory used everywhere else in this script),
# and must pass config.adminEmail explicitly since it is a `required` value
# (see templates/_helpers.tpl). This exact sequence caught a real release CI
# failure on the v0.11.0 tag (the packaged-chart steps had no --set at all).
echo "==> helm package + lint/template packaged chart (release.yml parity)"
PKG_DIR="${OUT}/pkg"
rm -rf "${PKG_DIR}"
mkdir -p "${PKG_DIR}"
helm package "${CHART}" --destination "${PKG_DIR}" >/dev/null
PKG_CHART="$(find "${PKG_DIR}" -maxdepth 1 -name '*.tgz' | head -1)"
if [[ -z "${PKG_CHART}" ]]; then
  echo "helm-template-verify: FAIL helm package did not produce a .tgz in ${PKG_DIR}" >&2
  exit 1
fi
helm lint "${PKG_CHART}" --set config.adminEmail=ci@example.com
helm template "${RELEASE_NAME}" "${PKG_CHART}" --set config.adminEmail=ci@example.com >/dev/null

echo "==> helm show values -> ${OUT}/all-values.yaml"
{
  echo "# Generated by scripts/helm-template-verify.sh"
  echo "# helm show values ${CHART}"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  helm show values "${CHART}"
} > "${OUT}/all-values.yaml"

scenarios=(
  "defaults:${CHART}/values.yaml"
  "ci:${CHART}/ci/ci-values.yaml"
  "minimal:${CHART}/examples/values-minimal.yaml"
  "external-db:${CHART}/examples/values-external-db.yaml"
  "full-test:${CHART}/examples/values-full-test.yaml"
)

for item in "${scenarios[@]}"; do
  name="${item%%:*}"
  values="${item#*:}"
  dest="${OUT}/rendered-${name}.yaml"
  echo "==> helm template ${RELEASE_NAME} [${name}] -> ${dest}"
  set_args=(--set "config.adminEmail=ci@example.com")
  case "${name}" in
    external-db)
      set_args+=(--set "postgresql.external.password=dummy")
      ;;
  esac
  helm template "${RELEASE_NAME}" "${CHART}" \
    -f "${values}" \
    "${set_args[@]}" \
    > "${dest}"
  count="$(grep -c '^kind:' "${dest}" || true)"
  echo "    resources: ${count}"
done

echo "==> spot-check full-test render"
grep -n "kind: ConfigMap" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "TRUST_PROXY_HOPS" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "kind: HorizontalPodAutoscaler" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "kind: Cluster" "${OUT}/rendered-full-test.yaml" | head -3 || true

echo "==> assert DB_SSL=verify when CloudNativePG is enabled (defaults + minimal)"
for name in defaults minimal; do
  rendered="${OUT}/rendered-${name}.yaml"
  if ! grep -qE 'DB_SSL:[[:space:]]*"?verify"?' "${rendered}"; then
    echo "helm-template-verify: FAIL missing DB_SSL=verify in ${name} render" >&2
    grep -n 'DB_SSL\|cloudnative' "${rendered}" | head -20 >&2 || true
    exit 1
  fi
done

fail() {
  echo "helm-template-verify: FAIL $*" >&2
  exit 1
}

assert_contains() {
  local actual="$1"
  local expected="$2"
  local message="$3"
  [[ "${actual}" == *"${expected}"* ]] || fail "${message}: missing ${expected}"
}

assert_not_contains() {
  local actual="$1"
  local unexpected="$2"
  local message="$3"
  [[ "${actual}" != *"${unexpected}"* ]] || fail "${message}: unexpectedly found ${unexpected}"
}

component_blocks() {
  local rendered="$1"
  local kind="$2"
  awk -v RS='---' -v expected_kind="${kind}" '
    {
      is_expected_kind = 0
      line_count = split($0, lines, "\n")
      for (line = 1; line <= line_count; line++) {
        if (lines[line] == "kind: " expected_kind) {
          is_expected_kind = 1
          break
        }
      }
    }
    is_expected_kind && index($0, "app.kubernetes.io/component: certops-controller") {
      print "---" $0
    }
  ' "${rendered}"
}

assert_controller_rbac_hardening() {
  local rendered="$1"
  local fallback_enabled="$2"
  local mode="${3:-observe}"
  local blocks
  local kind
  local secret_verbs
  local secret_verb

  for kind in Role ClusterRole; do
    blocks="$(component_blocks "${rendered}" "${kind}")"
    [[ -z "${blocks}" ]] && continue

    if printf '%s\n' "${blocks}" | grep -Eq "^[[:space:]]*-[[:space:]]*['\"]?\\*['\"]?[[:space:]]*$"; then
      fail "${kind} controller RBAC contains a wildcard resource or verb"
    fi

    assert_contains "${blocks}" $'    resources:\n      - certificaterequests\n    verbs:\n      - get\n      - list\n      - watch' "${kind} CertificateRequest read-only rule"

    if [[ "${mode}" == "observe" ]]; then
      assert_not_contains "${blocks}" $'      - create' "${kind} observe controller RBAC"
      assert_not_contains "${blocks}" $'      - patch' "${kind} observe controller RBAC"
    else
      assert_contains "${blocks}" $'    resources:\n      - certificates\n    verbs:\n      - get\n      - list\n      - watch\n      - create\n      - patch' "${kind} provision Certificate verbs"
    fi
    assert_not_contains "${blocks}" $'      - update' "${kind} controller RBAC"
    assert_not_contains "${blocks}" $'      - delete' "${kind} controller RBAC"

    if [[ "${fallback_enabled}" == "true" ]]; then
      assert_contains "${blocks}" $'    resources:\n      - secrets\n    verbs:\n      - get' "${kind} secret fallback rule"
      secret_verbs="$(printf '%s\n' "${blocks}" | awk '
        /^[[:space:]]+resources:/ { secret_rule = 0; collecting_verbs = 0; next }
        /^[[:space:]]+- secrets$/ { secret_rule = 1; next }
        secret_rule && /^[[:space:]]+verbs:/ { collecting_verbs = 1; next }
        collecting_verbs && /^[[:space:]]+- / { print $2; next }
        collecting_verbs { secret_rule = 0; collecting_verbs = 0 }
      ')"
      [[ -n "${secret_verbs}" ]] || fail "${kind} missing secret fallback verbs"
      while IFS= read -r secret_verb; do
        [[ "${secret_verb}" == "get" ]] || fail "${kind} secret fallback verb must be get, found ${secret_verb}"
      done <<< "${secret_verbs}"
    else
      assert_not_contains "${blocks}" 'secrets' "${kind} secret fallback disabled"
    fi
  done
}

render_controller() {
  local name="$1"
  shift
  local dest="${OUT}/certops-controller-${name}.yaml"
  echo "==> helm template ${RELEASE_NAME} [certops-controller:${name}] -> ${dest}" >&2
  helm template "${RELEASE_NAME}" "${CHART}" \
    "${controller_base_args[@]}" \
    "$@" \
    > "${dest}"
  printf '%s' "${dest}"
}

expect_controller_failure() {
  local name="$1"
  local expected="$2"
  shift 2
  local dest="${OUT}/certops-controller-invalid-${name}.log"
  echo "==> helm template ${RELEASE_NAME} [certops-controller invalid:${name}]" >&2
  if helm template "${RELEASE_NAME}" "${CHART}" \
    "${controller_base_args[@]}" \
    "$@" \
    > "${dest}" 2>&1; then
    fail "certops controller render unexpectedly succeeded: ${name}"
  fi
  if ! grep -Fq -- "${expected}" "${dest}"; then
    fail "certops controller failure ${name} did not mention ${expected}"
  fi
}

# Release validation retains an explicit, narrowly bounded controller
# capability surface across every supported mode/scope/fallback combination.
controller_base_args=(
  --namespace certops-system
  --set config.adminEmail=ci@example.com
  --set certops.controller.enabled=true
  --set certops.controller.api.url=https://api.tokentimer.example
  --set certops.controller.api.workspaceId=00000000-0000-4000-8000-000000000001
  --set certops.controller.api.clusterId=cluster-123
  --set certops.controller.apiToken.existingSecret=controller-api-token
  --set certops.controller.apiToken.key=token
)

echo "==> assert disabled CertOps controller emits no controller resources"
controller_disabled="${OUT}/certops-controller-disabled.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --namespace certops-system \
  --set config.adminEmail=ci@example.com \
  > "${controller_disabled}"
if grep -Fq 'app.kubernetes.io/component: certops-controller' "${controller_disabled}"; then
  fail "disabled CertOps controller rendered controller resources"
fi

# certops.controller.clusterWide defaults to true (values.yaml), so the
# literal chart default (no override) must render ClusterRole/ClusterRoleBinding.
controller_true_default="$(render_controller true-default)"
controller_true_default_cluster_role="$(component_blocks "${controller_true_default}" ClusterRole)"
controller_true_default_cluster_binding="$(component_blocks "${controller_true_default}" ClusterRoleBinding)"
assert_contains "${controller_true_default_cluster_role}" 'kind: ClusterRole' "chart-default ClusterRole"
assert_contains "${controller_true_default_cluster_binding}" 'kind: ClusterRoleBinding' "chart-default ClusterRoleBinding"
assert_controller_rbac_hardening "${controller_true_default}" false
if grep -Eq '^kind: Role(Binding)?$' "${controller_true_default}"; then
  fail "chart-default controller (clusterWide=true) rendered namespaced RBAC"
fi

# Explicit opt-out (clusterWide=false) still needs full namespace-scoped coverage.
controller_default="$(render_controller namespace-scoped --set certops.controller.clusterWide=false)"
controller_default_roles="$(component_blocks "${controller_default}" Role)"
controller_default_bindings="$(component_blocks "${controller_default}" RoleBinding)"
assert_contains "${controller_default_roles}" 'namespace: "certops-system"' "namespace-scoped default namespace Role"
assert_contains "${controller_default_bindings}" 'namespace: "certops-system"' "namespace-scoped default namespace RoleBinding"
assert_contains "${controller_default_roles}" 'cert-manager.io' "controller cert-manager group"
assert_contains "${controller_default_roles}" $'      - certificates' "controller Certificate resource"
assert_contains "${controller_default_roles}" $'      - certificaterequests' "controller CertificateRequest resource"
assert_contains "${controller_default_roles}" $'      - get\n      - list\n      - watch' "controller read verbs"
assert_controller_rbac_hardening "${controller_default}" false
if grep -Eq '^kind: ClusterRole(Binding)?$' "${controller_default}"; then
  fail "namespace-scoped controller rendered cluster-wide RBAC"
fi

controller_deployment="$(component_blocks "${controller_default}" Deployment)"
controller_service_accounts="$(component_blocks "${controller_default}" ServiceAccount)"
controller_default_network_policy="$(component_blocks "${controller_default}" NetworkPolicy)"
shared_service_account="$(awk -v RS='---' '
  index($0, "kind: ServiceAccount\n") &&
  !index($0, "app.kubernetes.io/component: certops-controller") { print "---" $0 }
' "${controller_default}")"
assert_contains "${controller_deployment}" 'replicas: 1' "single controller replica"
assert_contains "${controller_deployment}" 'automountServiceAccountToken: true' "controller deployment token mount"
assert_contains "${controller_deployment}" 'path: /healthz' "controller liveness probe"
assert_contains "${controller_deployment}" 'path: /readyz' "controller readiness probe"
assert_contains "${controller_deployment}" 'name: TOKENTIMER_API_TOKEN_FILE' "controller token-file environment"
assert_contains "${controller_deployment}" 'name: CERTOPS_WATCH_NAMESPACES' "controller default watch namespace"
assert_contains "${controller_deployment}" 'value: "certops-system"' "controller release namespace watch"
assert_contains "${controller_deployment}" 'secretName: "controller-api-token"' "controller existing token secret"
assert_contains "${controller_service_accounts}" 'automountServiceAccountToken: true' "controller service account token mount"
assert_contains "${shared_service_account}" 'automountServiceAccountToken: false' "shared service account token mount"
[[ -z "${controller_default_network_policy}" ]] || fail "controller NetworkPolicy rendered while chart policy is disabled"

controller_internal_api="$(render_controller internal-api-url --set-string certops.controller.api.url=http://tokentimer-api:4000)"
controller_internal_deployment="$(component_blocks "${controller_internal_api}" Deployment)"
assert_contains "${controller_internal_deployment}" 'value: "http://tokentimer-api:4000"' "valid internal controller API URL"

controller_multiple="$(render_controller namespace-multiple \
  --set certops.controller.clusterWide=false \
  --set certops.controller.watchNamespaces[0]=team-a \
  --set certops.controller.watchNamespaces[1]=team-b)"
controller_multiple_roles="$(component_blocks "${controller_multiple}" Role)"
assert_contains "${controller_multiple_roles}" 'namespace: "team-a"' "explicit namespace Role"
assert_contains "${controller_multiple_roles}" 'namespace: "team-b"' "explicit namespace Role"
assert_not_contains "${controller_multiple_roles}" 'namespace: "certops-system"' "explicit namespace Role"
assert_controller_rbac_hardening "${controller_multiple}" false

controller_secret_fallback="$(render_controller secret-fallback --set certops.controller.secretFallbackEnabled=true)"
assert_controller_rbac_hardening "${controller_secret_fallback}" true

controller_cluster_wide="$(render_controller cluster-wide --set certops.controller.clusterWide=true)"
controller_cluster_role="$(component_blocks "${controller_cluster_wide}" ClusterRole)"
controller_cluster_binding="$(component_blocks "${controller_cluster_wide}" ClusterRoleBinding)"
assert_contains "${controller_cluster_role}" 'kind: ClusterRole' "cluster-wide ClusterRole"
assert_contains "${controller_cluster_binding}" 'kind: ClusterRoleBinding' "cluster-wide ClusterRoleBinding"
assert_controller_rbac_hardening "${controller_cluster_wide}" false
if grep -Eq '^kind: Role(Binding)?$' "${controller_cluster_wide}"; then
  fail "cluster-wide controller rendered namespaced RBAC"
fi

controller_cluster_wide_secret_fallback="$(render_controller cluster-wide-secret-fallback \
  --set certops.controller.clusterWide=true \
  --set certops.controller.secretFallbackEnabled=true)"
assert_controller_rbac_hardening "${controller_cluster_wide_secret_fallback}" true

controller_numeric_strings="$(render_controller numeric-strings \
  --namespace 123 \
  --set certops.controller.clusterWide=false \
  --set-string certops.controller.watchNamespaces[0]=123 \
  --set-string certops.controller.apiToken.existingSecret=123 \
  --set-string certops.controller.apiToken.key=123)"
controller_numeric_roles="$(component_blocks "${controller_numeric_strings}" Role)"
controller_numeric_bindings="$(component_blocks "${controller_numeric_strings}" RoleBinding)"
controller_numeric_deployment="$(component_blocks "${controller_numeric_strings}" Deployment)"
assert_contains "${controller_numeric_roles}" 'namespace: "123"' "numeric namespace Role string"
assert_contains "${controller_numeric_bindings}" 'namespace: "123"' "numeric namespace RoleBinding string"
assert_contains "${controller_numeric_bindings}" $'    namespace: "123"' "numeric subject namespace string"
assert_contains "${controller_numeric_deployment}" 'secretName: "123"' "numeric Secret name string"
assert_contains "${controller_numeric_deployment}" '- key: "123"' "numeric Secret key string"

expect_controller_failure missing-api-url 'api.url' --set certops.controller.api.url=
expect_controller_failure missing-workspace-id 'api.workspaceId' --set certops.controller.api.workspaceId=
expect_controller_failure invalid-workspace-id 'workspaceId' --set-string certops.controller.api.workspaceId=workspace-123
expect_controller_failure missing-cluster-id 'api.clusterId' --set certops.controller.api.clusterId=
expect_controller_failure missing-token-secret 'apiToken.existingSecret' --set certops.controller.apiToken.existingSecret=
expect_controller_failure missing-token-key 'apiToken.key' --set certops.controller.apiToken.key=
expect_controller_failure invalid-mode 'mode' --set certops.controller.mode=invalid
controller_provision="$(render_controller provision-mode --set certops.controller.mode=provision)"
controller_provision_roles="$(component_blocks "${controller_provision}" Role)"
controller_provision_deployment="$(component_blocks "${controller_provision}" Deployment)"
assert_controller_rbac_hardening "${controller_provision}" false provision
assert_contains "${controller_provision_deployment}" $'strategy:\n    type: Recreate' "provision no-overlap strategy"
assert_contains "${controller_provision_deployment}" $'name: CERTOPS_CONTROLLER_MODE\n              value: "provision"' "provision runtime mode"

controller_provision_fallback="$(render_controller provision-fallback \
  --set certops.controller.mode=provision \
  --set certops.controller.secretFallbackEnabled=true)"
assert_controller_rbac_hardening "${controller_provision_fallback}" true provision

controller_provision_cluster_wide="$(render_controller provision-cluster-wide \
  --set certops.controller.mode=provision \
  --set certops.controller.clusterWide=true)"
controller_provision_cluster_role="$(component_blocks "${controller_provision_cluster_wide}" ClusterRole)"
controller_provision_cluster_deployment="$(component_blocks "${controller_provision_cluster_wide}" Deployment)"
assert_contains "${controller_provision_cluster_role}" 'kind: ClusterRole' "provision cluster-wide ClusterRole"
assert_contains "${controller_provision_cluster_deployment}" $'name: CERTOPS_CLUSTER_WIDE\n              value: "true"' "provision cluster-wide runtime policy"
assert_controller_rbac_hardening "${controller_provision_cluster_wide}" false provision
if grep -Eq '^kind: Role(Binding)?$' "${controller_provision_cluster_wide}"; then
  fail "cluster-wide provision controller rendered namespaced RBAC"
fi

controller_provision_cluster_fallback="$(render_controller provision-cluster-wide-fallback \
  --set certops.controller.mode=provision \
  --set certops.controller.clusterWide=true \
  --set certops.controller.secretFallbackEnabled=true)"
assert_controller_rbac_hardening "${controller_provision_cluster_fallback}" true provision

expect_controller_failure replica-count-two 'replicaCount' --set certops.controller.replicaCount=2
expect_controller_failure cluster-wide-with-namespaces 'watchNamespaces' \
  --set certops.controller.clusterWide=true \
  --set certops.controller.watchNamespaces[0]=team-a
expect_controller_failure invalid-watch-namespace 'watchNamespaces' \
  --set certops.controller.clusterWide=false \
  --set-string certops.controller.watchNamespaces[0]=Not_Valid
expect_controller_failure network-policy-without-kube-api-cidrs 'kubeApiServerCidrs' --set networkPolicy.enabled=true
expect_controller_failure api-url-userinfo 'api.url' --set-string certops.controller.api.url=https://user:password@example.com
expect_controller_failure api-url-no-host 'api.url' --set-string certops.controller.api.url=https://
expect_controller_failure api-url-invalid-host 'api.url' --set-string certops.controller.api.url=http://?invalid
expect_controller_failure api-url-invalid-port 'api.url' --set-string certops.controller.api.url=https://example.com:999999

expect_controller_failure raw-token-value 'apiToken' --set-string certops.controller.apiToken.value=raw-controller-token
if grep -Fq 'raw-controller-token' "${OUT}"/certops-controller-*.yaml; then
  fail "raw controller token marker rendered into a manifest"
fi

controller_network_policy="$(render_controller network-policy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=192.0.2.10/32 \
  --set networkPolicy.egress.kubeApiServerCidrs[1]=192.0.2.11/32)"
controller_policy="$(component_blocks "${controller_network_policy}" NetworkPolicy)"
assert_contains "${controller_policy}" 'k8s-app: kube-dns' "controller DNS egress"
assert_contains "${controller_policy}" 'app.kubernetes.io/component: api' "controller in-chart API egress"
assert_contains "${controller_policy}" 'cidr: "192.0.2.10/32"' "controller first Kubernetes API egress"
assert_contains "${controller_policy}" 'cidr: "192.0.2.11/32"' "controller HA Kubernetes API egress"
assert_contains "${controller_policy}" 'port: 443' "controller Kubernetes API port"
assert_not_contains "${controller_policy}" 'ingress:' "controller NetworkPolicy ingress"
assert_not_contains "${controller_policy}" '0.0.0.0/0' "controller NetworkPolicy broad egress"
assert_not_contains "${controller_policy}" 'port: 5432' "controller NetworkPolicy database egress"
assert_not_contains "${controller_policy}" 'port: 25' "controller NetworkPolicy SMTP egress"
assert_not_contains "${controller_policy}" 'port: 465' "controller NetworkPolicy SMTP egress"
assert_not_contains "${controller_policy}" 'port: 587' "controller NetworkPolicy SMTP egress"
assert_not_contains "${controller_policy}" 'port: 9091' "controller NetworkPolicy metrics egress"

controller_network_custom_kube_port="$(render_controller network-policy-custom-kube-port \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=192.0.2.10/32 \
  --set networkPolicy.egress.kubeApiServerPort=6443)"
controller_custom_kube_policy="$(component_blocks "${controller_network_custom_kube_port}" NetworkPolicy)"
assert_contains "${controller_custom_kube_policy}" 'port: 6443' "custom Kubernetes API port"

expect_controller_failure network-policy-disabled-api 'controllerApiCidrs' \
  --set api.enabled=false \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=192.0.2.10/32

controller_network_cidrs="$(render_controller network-policy-cidrs \
  --set api.enabled=false \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=192.0.2.10/32 \
  --set networkPolicy.egress.controllerApiCidrs[0]=198.51.100.0/24)"
controller_cidr_policy="$(component_blocks "${controller_network_cidrs}" NetworkPolicy)"
assert_contains "${controller_cidr_policy}" 'cidr: "198.51.100.0/24"' "controller explicit API CIDR egress"
assert_not_contains "${controller_cidr_policy}" 'app.kubernetes.io/component: api' "controller external API CIDR egress"

# ---------------------------------------------------------------------------
# Corporate proxy support (config.useEnvProxy / networkPolicy.egress.proxy*)
# ---------------------------------------------------------------------------

expect_proxy_failure() {
  local name="$1"
  local expected="$2"
  shift 2
  local dest="${OUT}/proxy-invalid-${name}.log"
  echo "==> helm template ${RELEASE_NAME} [proxy invalid:${name}]" >&2
  if helm template "${RELEASE_NAME}" "${CHART}" \
    --set config.adminEmail=ci@example.com \
    "$@" \
    > "${dest}" 2>&1; then
    fail "proxy render unexpectedly succeeded: ${name}"
  fi
  if ! grep -Fq -- "${expected}" "${dest}"; then
    fail "proxy failure ${name} did not mention ${expected}"
  fi
}

echo "==> assert proxy env vars and secretRef render when config.useEnvProxy=true"
proxy_enabled="${OUT}/rendered-proxy-enabled.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --set config.adminEmail=ci@example.com \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set config.noProxy=custom.internal \
  > "${proxy_enabled}"
assert_contains "$(cat "${proxy_enabled}")" 'NODE_USE_ENV_PROXY: "1"' "proxy enabled NODE_USE_ENV_PROXY"
proxy_no_proxy_line="$(grep -m1 '^  NO_PROXY:' "${proxy_enabled}" || true)"
[[ -n "${proxy_no_proxy_line}" ]] || fail "proxy enabled render missing NO_PROXY key"
assert_contains "${proxy_no_proxy_line}" 'localhost' "proxy enabled NO_PROXY localhost entry"
assert_contains "${proxy_no_proxy_line}" '127.0.0.1' "proxy enabled NO_PROXY loopback IPv4 entry"
assert_contains "${proxy_no_proxy_line}" '::1' "proxy enabled NO_PROXY loopback IPv6 entry"
assert_contains "${proxy_no_proxy_line}" "${RELEASE_NAME}-api" "proxy enabled NO_PROXY in-cluster API hostname"
assert_contains "${proxy_no_proxy_line}" '.svc' "proxy enabled NO_PROXY .svc suffix"
assert_contains "${proxy_no_proxy_line}" '.cluster.local' "proxy enabled NO_PROXY .cluster.local suffix"
assert_contains "${proxy_no_proxy_line}" 'custom.internal' "proxy enabled NO_PROXY custom entry"
proxy_enabled_secretref_count="$(grep -c 'name: corporate-proxy' "${proxy_enabled}" || true)"
[[ "${proxy_enabled_secretref_count}" -ge 2 ]] || fail "proxy secretRef should mount on api Deployment and worker CronJobs (found ${proxy_enabled_secretref_count})"

echo "==> assert proxy env vars and secretRef absent by default (config.useEnvProxy=false)"
proxy_disabled="${OUT}/rendered-proxy-disabled.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --set config.adminEmail=ci@example.com \
  > "${proxy_disabled}"
assert_not_contains "$(cat "${proxy_disabled}")" 'NODE_USE_ENV_PROXY' "default-safe proxy render"
assert_not_contains "$(cat "${proxy_disabled}")" 'NO_PROXY' "default-safe proxy render"

expect_proxy_failure use-env-proxy-without-secret 'proxyExistingSecret' \
  --set config.useEnvProxy=true

echo "==> assert webhook host allowlist env vars render"
webhook_hosts_rendered="${OUT}/rendered-webhook-hosts.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --set config.adminEmail=ci@example.com \
  --set config.webhookProviderHosts=custom.example.com \
  --set config.webhookExtraProviderHosts=extra.example.com \
  --set config.webhookAllowAllHosts=true \
  > "${webhook_hosts_rendered}"
assert_contains "$(cat "${webhook_hosts_rendered}")" 'WEBHOOK_PROVIDER_HOSTS: "custom.example.com"' "webhook provider hosts"
assert_contains "$(cat "${webhook_hosts_rendered}")" 'WEBHOOK_EXTRA_PROVIDER_HOSTS: "extra.example.com"' "webhook extra provider hosts"
assert_contains "$(cat "${webhook_hosts_rendered}")" 'WEBHOOK_ALLOW_ALL_HOSTS: "true"' "webhook allow all hosts"

expect_proxy_failure network-policy-without-proxy-cidrs 'proxyCidrs' \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set networkPolicy.enabled=true \
  --set-json 'networkPolicy.egress.proxyCidrs=[]'
expect_proxy_failure proxy-cidrs-without-ports 'networkPolicy.egress.proxyPorts' \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.proxyCidrs[0]=10.0.0.0/8 \
  --set-json 'networkPolicy.egress.proxyPorts=[]'
expect_proxy_failure proxy-port-out-of-range 'networkPolicy.egress.proxyPorts' \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.proxyCidrs[0]=10.0.0.0/8 \
  --set-string networkPolicy.egress.proxyPorts[0]=99999
expect_proxy_failure proxy-port-not-a-number 'networkPolicy.egress.proxyPorts' \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.proxyCidrs[0]=10.0.0.0/8 \
  --set-string networkPolicy.egress.proxyPorts[0]=notanumber

echo "==> assert NetworkPolicy proxy egress renders for api and worker when useEnvProxy=true"
proxy_network_policy="${OUT}/rendered-proxy-network-policy.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --set config.adminEmail=ci@example.com \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.proxyCidrs[0]=192.0.2.50/32 \
  --set networkPolicy.egress.proxyPorts[0]=3128 \
  > "${proxy_network_policy}"
assert_contains "$(cat "${proxy_network_policy}")" 'cidr: 192.0.2.50/32' "proxy NetworkPolicy CIDR present"
assert_contains "$(cat "${proxy_network_policy}")" 'port: 3128' "proxy NetworkPolicy port present"
proxy_policy_blocks_count="$(grep -c 'cidr: 192.0.2.50/32' "${proxy_network_policy}" || true)"
[[ "${proxy_policy_blocks_count}" -ge 2 ]] || fail "proxy NetworkPolicy CIDR should render for both api and worker (found ${proxy_policy_blocks_count})"

echo "==> assert NetworkPolicy proxy egress absent when useEnvProxy=false (default) even with proxyCidrs set"
proxy_network_policy_disabled="${OUT}/rendered-proxy-network-policy-disabled.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --set config.adminEmail=ci@example.com \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.proxyCidrs[0]=192.0.2.50/32 \
  --set networkPolicy.egress.proxyPorts[0]=3128 \
  > "${proxy_network_policy_disabled}"
assert_not_contains "$(cat "${proxy_network_policy_disabled}")" '192.0.2.50/32' "proxy NetworkPolicy gated on useEnvProxy"

echo "==> assert CertOps controller receives no proxy vars or egress even when proxy is enabled"
controller_with_proxy="$(render_controller with-proxy-enabled \
  --set config.useEnvProxy=true \
  --set config.proxyExistingSecret=corporate-proxy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=192.0.2.10/32 \
  --set networkPolicy.egress.proxyCidrs[0]=192.0.2.50/32 \
  --set networkPolicy.egress.proxyPorts[0]=3128)"
controller_with_proxy_deployment="$(component_blocks "${controller_with_proxy}" Deployment)"
controller_with_proxy_policy="$(component_blocks "${controller_with_proxy}" NetworkPolicy)"
assert_not_contains "${controller_with_proxy_deployment}" 'NODE_USE_ENV_PROXY' "controller Deployment excluded from proxy env"
assert_not_contains "${controller_with_proxy_deployment}" 'name: corporate-proxy' "controller Deployment excluded from proxy secretRef"
assert_not_contains "${controller_with_proxy_policy}" '192.0.2.50/32' "controller NetworkPolicy excluded from proxy egress"

echo "helm-template-verify: ok -> ${OUT}"
