#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHART="${REPO_ROOT}/deploy/helm"
OUT="${REPO_ROOT}/.build/helm-template-verify"
RELEASE_NAME="${HELM_RELEASE_NAME:-tokentimer}"

if ! command -v helm >/dev/null 2>&1; then
  HELM_DIR="$(mktemp -d)"
  trap 'rm -rf "${HELM_DIR}"' EXIT
  curl -fsSL https://get.helm.sh/helm-v3.20.1-linux-amd64.tar.gz \
    | tar -xz -C "${HELM_DIR}"
  export PATH="${HELM_DIR}/linux-amd64:${PATH}"
fi

helm version

helm dependency build "${CHART}" 2>/dev/null || true

mkdir -p "${OUT}"

echo "==> helm lint (ci-values)"
helm lint "${CHART}" -f "${CHART}/ci/ci-values.yaml"

echo "==> helm show values -> ${OUT}/all-values.yaml"
{
  echo "# Generated by scripts/helm-template-verify.sh"
  echo "# helm show values ${CHART}"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  helm show values "${CHART}"
} > "${OUT}/all-values.yaml"

scenarios=(
  "defaults:${CHART}/values.yaml"
  "ci:${CHART}/ci/ci-values.yaml"
  "minimal:${CHART}/examples/values-minimal.yaml"
  "external-db:${CHART}/examples/values-external-db.yaml"
  "full-test:${CHART}/examples/values-full-test.yaml"
)

for item in "${scenarios[@]}"; do
  name="${item%%:*}"
  values="${item#*:}"
  dest="${OUT}/rendered-${name}.yaml"
  echo "==> helm template ${RELEASE_NAME} [${name}] -> ${dest}"
  set_args=(--set "config.adminEmail=ci@example.com")
  case "${name}" in
    external-db)
      set_args+=(--set "postgresql.external.password=dummy")
      ;;
  esac
  helm template "${RELEASE_NAME}" "${CHART}" \
    -f "${values}" \
    "${set_args[@]}" \
    > "${dest}"
  count="$(grep -c '^kind:' "${dest}" || true)"
  echo "    resources: ${count}"
done

echo "==> spot-check full-test render"
grep -n "kind: ConfigMap" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "TRUST_PROXY_HOPS" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "kind: HorizontalPodAutoscaler" "${OUT}/rendered-full-test.yaml" | head -3 || true
grep -n "kind: Cluster" "${OUT}/rendered-full-test.yaml" | head -3 || true

echo "==> assert DB_SSL=verify when CloudNativePG is enabled (defaults + minimal)"
for name in defaults minimal; do
  rendered="${OUT}/rendered-${name}.yaml"
  if ! grep -qE 'DB_SSL:[[:space:]]*"?verify"?' "${rendered}"; then
    echo "helm-template-verify: FAIL missing DB_SSL=verify in ${name} render" >&2
    grep -n 'DB_SSL\|cloudnative' "${rendered}" | head -20 >&2 || true
    exit 1
  fi
done

fail() {
  echo "helm-template-verify: FAIL $*" >&2
  exit 1
}

assert_contains() {
  local actual="$1"
  local expected="$2"
  local message="$3"
  [[ "${actual}" == *"${expected}"* ]] || fail "${message}: missing ${expected}"
}

assert_not_contains() {
  local actual="$1"
  local unexpected="$2"
  local message="$3"
  [[ "${actual}" != *"${unexpected}"* ]] || fail "${message}: unexpectedly found ${unexpected}"
}

component_blocks() {
  local rendered="$1"
  local kind="$2"
  awk -v RS='---' -v expected_kind="${kind}" '
    {
      is_expected_kind = 0
      line_count = split($0, lines, "\n")
      for (line = 1; line <= line_count; line++) {
        if (lines[line] == "kind: " expected_kind) {
          is_expected_kind = 1
          break
        }
      }
    }
    is_expected_kind && index($0, "app.kubernetes.io/component: certops-controller") {
      print "---" $0
    }
  ' "${rendered}"
}

assert_controller_rbac_hardening() {
  local rendered="$1"
  local fallback_enabled="$2"
  local blocks
  local kind
  local secret_verbs
  local secret_verb

  for kind in Role ClusterRole; do
    blocks="$(component_blocks "${rendered}" "${kind}")"
    [[ -z "${blocks}" ]] && continue

    assert_not_contains "${blocks}" $'      - create' "${kind} controller RBAC"
    assert_not_contains "${blocks}" $'      - update' "${kind} controller RBAC"
    assert_not_contains "${blocks}" $'      - patch' "${kind} controller RBAC"
    assert_not_contains "${blocks}" $'      - delete' "${kind} controller RBAC"

    if [[ "${fallback_enabled}" == "true" ]]; then
      assert_contains "${blocks}" $'    resources:\n      - secrets\n    verbs:\n      - get' "${kind} secret fallback rule"
      secret_verbs="$(printf '%s\n' "${blocks}" | awk '
        /^[[:space:]]+resources:/ { secret_rule = 0; collecting_verbs = 0; next }
        /^[[:space:]]+- secrets$/ { secret_rule = 1; next }
        secret_rule && /^[[:space:]]+verbs:/ { collecting_verbs = 1; next }
        collecting_verbs && /^[[:space:]]+- / { print $2; next }
        collecting_verbs { secret_rule = 0; collecting_verbs = 0 }
      ')"
      [[ -n "${secret_verbs}" ]] || fail "${kind} missing secret fallback verbs"
      while IFS= read -r secret_verb; do
        [[ "${secret_verb}" == "get" ]] || fail "${kind} secret fallback verb must be get, found ${secret_verb}"
      done <<< "${secret_verbs}"
    else
      assert_not_contains "${blocks}" 'secrets' "${kind} secret fallback disabled"
    fi
  done
}

render_controller() {
  local name="$1"
  shift
  local dest="${OUT}/certops-controller-${name}.yaml"
  echo "==> helm template ${RELEASE_NAME} [certops-controller:${name}] -> ${dest}" >&2
  helm template "${RELEASE_NAME}" "${CHART}" \
    "${controller_base_args[@]}" \
    "$@" \
    > "${dest}"
  printf '%s' "${dest}"
}

expect_controller_failure() {
  local name="$1"
  shift
  local dest="${OUT}/certops-controller-invalid-${name}.log"
  echo "==> helm template ${RELEASE_NAME} [certops-controller invalid:${name}]" >&2
  if helm template "${RELEASE_NAME}" "${CHART}" \
    "${controller_base_args[@]}" \
    "$@" \
    > "${dest}" 2>&1; then
    fail "certops controller render unexpectedly succeeded: ${name}"
  fi
}

# M3-A3 is intentionally a chart-only controller slice. Keep the following
# renders release-blocking so a values change cannot broaden the controller's
# identity, RBAC, or egress before runtime reconciliation exists.
controller_base_args=(
  --namespace certops-system
  --set config.adminEmail=ci@example.com
  --set certops.controller.enabled=true
  --set certops.controller.api.url=https://api.tokentimer.example
  --set certops.controller.api.workspaceId=workspace-123
  --set certops.controller.api.clusterId=cluster-123
  --set certops.controller.apiToken.existingSecret=controller-api-token
  --set certops.controller.apiToken.key=token
)

echo "==> assert disabled CertOps controller emits no controller resources"
controller_disabled="${OUT}/certops-controller-disabled.yaml"
helm template "${RELEASE_NAME}" "${CHART}" \
  --namespace certops-system \
  --set config.adminEmail=ci@example.com \
  > "${controller_disabled}"
if grep -Fq 'app.kubernetes.io/component: certops-controller' "${controller_disabled}"; then
  fail "disabled CertOps controller rendered controller resources"
fi

controller_default="$(render_controller namespace-default)"
controller_default_roles="$(component_blocks "${controller_default}" Role)"
controller_default_bindings="$(component_blocks "${controller_default}" RoleBinding)"
assert_contains "${controller_default_roles}" 'namespace: "certops-system"' "default namespace Role"
assert_contains "${controller_default_bindings}" 'namespace: "certops-system"' "default namespace RoleBinding"
assert_contains "${controller_default_roles}" 'cert-manager.io' "controller cert-manager group"
assert_contains "${controller_default_roles}" $'      - certificates\n      - certificaterequests' "controller cert-manager resources"
assert_contains "${controller_default_roles}" $'      - get\n      - list\n      - watch' "controller read verbs"
assert_controller_rbac_hardening "${controller_default}" false
if grep -Eq '^kind: ClusterRole(Binding)?$' "${controller_default}"; then
  fail "namespace-scoped controller rendered cluster-wide RBAC"
fi

controller_deployment="$(component_blocks "${controller_default}" Deployment)"
controller_service_accounts="$(component_blocks "${controller_default}" ServiceAccount)"
shared_service_account="$(awk -v RS='---' '
  index($0, "kind: ServiceAccount\n") &&
  !index($0, "app.kubernetes.io/component: certops-controller") { print "---" $0 }
' "${controller_default}")"
assert_contains "${controller_deployment}" 'replicas: 1' "single controller replica"
assert_contains "${controller_deployment}" 'automountServiceAccountToken: true' "controller deployment token mount"
assert_contains "${controller_deployment}" 'path: /healthz' "controller liveness probe"
assert_contains "${controller_deployment}" 'path: /readyz' "controller readiness probe"
assert_contains "${controller_deployment}" 'name: TOKENTIMER_API_TOKEN_FILE' "controller token-file environment"
assert_contains "${controller_deployment}" 'name: CERTOPS_WATCH_NAMESPACES' "controller default watch namespace"
assert_contains "${controller_deployment}" 'value: "certops-system"' "controller release namespace watch"
assert_contains "${controller_deployment}" 'secretName: "controller-api-token"' "controller existing token secret"
assert_contains "${controller_service_accounts}" 'automountServiceAccountToken: true' "controller service account token mount"
assert_contains "${shared_service_account}" 'automountServiceAccountToken: false' "shared service account token mount"

controller_internal_api="$(render_controller internal-api-url --set-string certops.controller.api.url=http://tokentimer-api:4000)"
controller_internal_deployment="$(component_blocks "${controller_internal_api}" Deployment)"
assert_contains "${controller_internal_deployment}" 'value: "http://tokentimer-api:4000"' "valid internal controller API URL"

controller_multiple="$(render_controller namespace-multiple \
  --set certops.controller.watchNamespaces[0]=team-a \
  --set certops.controller.watchNamespaces[1]=team-b)"
controller_multiple_roles="$(component_blocks "${controller_multiple}" Role)"
assert_contains "${controller_multiple_roles}" 'namespace: "team-a"' "explicit namespace Role"
assert_contains "${controller_multiple_roles}" 'namespace: "team-b"' "explicit namespace Role"
assert_not_contains "${controller_multiple_roles}" 'namespace: "certops-system"' "explicit namespace Role"
assert_controller_rbac_hardening "${controller_multiple}" false

controller_secret_fallback="$(render_controller secret-fallback --set certops.controller.secretFallbackEnabled=true)"
assert_controller_rbac_hardening "${controller_secret_fallback}" true

controller_cluster_wide="$(render_controller cluster-wide --set certops.controller.clusterWide=true)"
controller_cluster_role="$(component_blocks "${controller_cluster_wide}" ClusterRole)"
controller_cluster_binding="$(component_blocks "${controller_cluster_wide}" ClusterRoleBinding)"
assert_contains "${controller_cluster_role}" 'kind: ClusterRole' "cluster-wide ClusterRole"
assert_contains "${controller_cluster_binding}" 'kind: ClusterRoleBinding' "cluster-wide ClusterRoleBinding"
assert_controller_rbac_hardening "${controller_cluster_wide}" false
if grep -Eq '^kind: Role(Binding)?$' "${controller_cluster_wide}"; then
  fail "cluster-wide controller rendered namespaced RBAC"
fi

controller_cluster_wide_secret_fallback="$(render_controller cluster-wide-secret-fallback \
  --set certops.controller.clusterWide=true \
  --set certops.controller.secretFallbackEnabled=true)"
assert_controller_rbac_hardening "${controller_cluster_wide_secret_fallback}" true

controller_numeric_strings="$(render_controller numeric-strings \
  --namespace 123 \
  --set-string certops.controller.watchNamespaces[0]=123 \
  --set-string certops.controller.apiToken.existingSecret=123 \
  --set-string certops.controller.apiToken.key=123)"
controller_numeric_roles="$(component_blocks "${controller_numeric_strings}" Role)"
controller_numeric_bindings="$(component_blocks "${controller_numeric_strings}" RoleBinding)"
controller_numeric_deployment="$(component_blocks "${controller_numeric_strings}" Deployment)"
assert_contains "${controller_numeric_roles}" 'namespace: "123"' "numeric namespace Role string"
assert_contains "${controller_numeric_bindings}" 'namespace: "123"' "numeric namespace RoleBinding string"
assert_contains "${controller_numeric_bindings}" $'    namespace: "123"' "numeric subject namespace string"
assert_contains "${controller_numeric_deployment}" 'secretName: "123"' "numeric Secret name string"
assert_contains "${controller_numeric_deployment}" '- key: "123"' "numeric Secret key string"

expect_controller_failure missing-api-url --set certops.controller.api.url=
expect_controller_failure missing-workspace-id --set certops.controller.api.workspaceId=
expect_controller_failure missing-cluster-id --set certops.controller.api.clusterId=
expect_controller_failure missing-token-secret --set certops.controller.apiToken.existingSecret=
expect_controller_failure missing-token-key --set certops.controller.apiToken.key=
expect_controller_failure invalid-mode --set certops.controller.mode=invalid
expect_controller_failure provision-mode --set certops.controller.mode=provision
expect_controller_failure replica-count-two --set certops.controller.replicaCount=2
expect_controller_failure cluster-wide-with-namespaces \
  --set certops.controller.clusterWide=true \
  --set certops.controller.watchNamespaces[0]=team-a
expect_controller_failure network-policy-without-kube-api-cidrs --set networkPolicy.enabled=true
expect_controller_failure api-url-userinfo --set-string certops.controller.api.url=https://user:password@example.com
expect_controller_failure api-url-no-host --set-string certops.controller.api.url=https://
expect_controller_failure api-url-invalid-host --set-string certops.controller.api.url=http://?invalid
expect_controller_failure api-url-invalid-port --set-string certops.controller.api.url=https://example.com:999999

expect_controller_failure raw-token-value --set-string certops.controller.apiToken.value=raw-controller-token
if grep -Fq 'raw-controller-token' "${OUT}"/certops-controller-*.yaml; then
  fail "raw controller token marker rendered into a manifest"
fi

controller_network_policy="$(render_controller network-policy \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=10.96.0.1/32)"
controller_policy="$(component_blocks "${controller_network_policy}" NetworkPolicy)"
assert_contains "${controller_policy}" 'k8s-app: kube-dns' "controller DNS egress"
assert_contains "${controller_policy}" 'app.kubernetes.io/component: api' "controller in-chart API egress"
assert_contains "${controller_policy}" 'cidr: "10.96.0.1/32"' "controller Kubernetes API egress"
assert_contains "${controller_policy}" 'port: 443' "controller Kubernetes API port"
assert_not_contains "${controller_policy}" 'ingress:' "controller NetworkPolicy ingress"
assert_not_contains "${controller_policy}" '0.0.0.0/0' "controller NetworkPolicy broad egress"
assert_not_contains "${controller_policy}" 'port: 5432' "controller NetworkPolicy database egress"
assert_not_contains "${controller_policy}" 'port: 25' "controller NetworkPolicy SMTP egress"
assert_not_contains "${controller_policy}" 'port: 465' "controller NetworkPolicy SMTP egress"
assert_not_contains "${controller_policy}" 'port: 587' "controller NetworkPolicy SMTP egress"
assert_not_contains "${controller_policy}" 'port: 9091' "controller NetworkPolicy metrics egress"

expect_controller_failure network-policy-disabled-api \
  --set api.enabled=false \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=10.96.0.1/32

controller_network_cidrs="$(render_controller network-policy-cidrs \
  --set api.enabled=false \
  --set networkPolicy.enabled=true \
  --set networkPolicy.egress.kubeApiServerCidrs[0]=10.96.0.1/32 \
  --set networkPolicy.egress.controllerApiCidrs[0]=198.51.100.0/24)"
controller_cidr_policy="$(component_blocks "${controller_network_cidrs}" NetworkPolicy)"
assert_contains "${controller_cidr_policy}" 'cidr: "198.51.100.0/24"' "controller explicit API CIDR egress"
assert_not_contains "${controller_cidr_policy}" 'app.kubernetes.io/component: api' "controller external API CIDR egress"

echo "helm-template-verify: ok -> ${OUT}"
